import 'package:flutter/material.dart';
import 'package:laptop_app/models/food.dart';

class Restuarent extends ChangeNotifier {
  final List<Food> _menu = [
    Food(
      name: "Classic Cheese",
      description: "A juicy peet baty",
      imgPath: "lib/assests/Images/Laptopone.jpg",
      price: 0.99,
      category: FoodCategory.burgers,
      availableAddons: [
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
      ],
    ),
    Food(
      name: "Classic Cheese",
      description: "A juicy peet baty",
      imgPath: "lib/assests/Images/Laptopone.jpg",
      price: 0.99,
      category: FoodCategory.burgers,
      availableAddons: [
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
      ],
    ),
    Food(
      name: "Classic Cheese",
      description: "A juicy peet baty",
      imgPath: "lib/assests/Images/Laptopone.jpg",
      price: 0.99,
      category: FoodCategory.burgers,
      availableAddons: [
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
      ],
    ),
    Food(
      name: "Classic Cheese",
      description: "A juicy peet baty",
      imgPath: "lib/assests/Images/Laptopone.jpg",
      price: 0.99,
      category: FoodCategory.burgers,
      availableAddons: [
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
      ],
    ),
    Food(
      name: "Classic Cheese",
      description: "A juicy peet baty",
      imgPath: "lib/assests/Images/Laptopone.jpg",
      price: 0.99,
      category: FoodCategory.burgers,
      availableAddons: [
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
      ],
    ),
    Food(
      name: "Classic Cheese",
      description: "A juicy peet baty",
      imgPath: "lib/assests/Images/Laptopone.jpg",
      price: 0.99,
      category: FoodCategory.salad,
      availableAddons: [
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
      ],
    ),
    Food(
      name: "Classic Cheese",
      description: "A juicy peet baty",
      imgPath: "lib/assests/Images/Laptopone.jpg",
      price: 0.99,
      category: FoodCategory.salad,
      availableAddons: [
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
      ],
    ),
    Food(
      name: "Classic Cheese",
      description: "A juicy peet baty",
      imgPath: "lib/assests/Images/Laptopone.jpg",
      price: 0.99,
      category: FoodCategory.salad,
      availableAddons: [
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
      ],
    ),
    Food(
      name: "Classic Cheese",
      description: "A juicy peet baty",
      imgPath: "lib/assests/Images/Laptopone.jpg",
      price: 0.99,
      category: FoodCategory.salad,
      availableAddons: [
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
      ],
    ),
    Food(
      name: "Classic Cheese",
      description: "A juicy peet baty",
      imgPath: "lib/assests/Images/Laptopone.jpg",
      price: 0.99,
      category: FoodCategory.salad,
      availableAddons: [
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
      ],
    ),
    Food(
      name: "Classic Cheese",
      description: "A juicy peet baty",
      imgPath: "lib/assests/Images/Laptopone.jpg",
      price: 0.99,
      category: FoodCategory.sides,
      availableAddons: [
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
      ],
    ),
    Food(
      name: "Classic Cheese",
      description: "A juicy peet baty",
      imgPath: "lib/assests/Images/Laptopone.jpg",
      price: 0.99,
      category: FoodCategory.sides,
      availableAddons: [
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
      ],
    ),
    Food(
      name: "Classic Cheese",
      description: "A juicy peet baty",
      imgPath: "lib/assests/Images/Laptopone.jpg",
      price: 0.99,
      category: FoodCategory.sides,
      availableAddons: [
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
      ],
    ),
    Food(
      name: "Classic Cheese",
      description: "A juicy peet baty",
      imgPath: "lib/assests/Images/Laptopone.jpg",
      price: 0.99,
      category: FoodCategory.sides,
      availableAddons: [
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
      ],
    ),
    Food(
      name: "Classic Cheese",
      description: "A juicy peet baty",
      imgPath: "lib/assests/Images/Laptopone.jpg",
      price: 0.99,
      category: FoodCategory.sides,
      availableAddons: [
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
      ],
    ),
    Food(
      name: "Classic Cheese",
      description: "A juicy peet baty",
      imgPath: "lib/assests/Images/Laptopone.jpg",
      price: 0.99,
      category: FoodCategory.desserts,
      availableAddons: [
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
      ],
    ),
    Food(
      name: "Classic Cheese",
      description: "A juicy peet baty",
      imgPath: "lib/assests/Images/Laptopone.jpg",
      price: 0.99,
      category: FoodCategory.sides,
      availableAddons: [
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
      ],
    ),
    Food(
      name: "Classic Cheese",
      description: "A juicy peet baty",
      imgPath: "lib/assests/Images/Laptopone.jpg",
      price: 0.99,
      category: FoodCategory.desserts,
      availableAddons: [
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
      ],
    ),
    Food(
      name: "Classic Cheese",
      description: "A juicy peet baty",
      imgPath: "lib/assests/Images/Laptopone.jpg",
      price: 0.99,
      category: FoodCategory.desserts,
      availableAddons: [
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
      ],
    ),
    Food(
      name: "Classic Cheese",
      description: "A juicy peet baty",
      imgPath: "lib/assests/Images/Laptopone.jpg",
      price: 0.99,
      category: FoodCategory.desserts,
      availableAddons: [
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
      ],
    ),
    Food(
      name: "Classic Cheese",
      description: "A juicy peet baty",
      imgPath: "lib/assests/Images/Laptopone.jpg",
      price: 0.99,
      category: FoodCategory.drinks,
      availableAddons: [
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
      ],
    ),
    Food(
      name: "Classic Cheese",
      description: "A juicy peet baty",
      imgPath: "lib/assests/Images/Laptopone.jpg",
      price: 0.99,
      category: FoodCategory.drinks,
      availableAddons: [
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
      ],
    ),
    Food(
      name: "Classic Cheese",
      description: "A juicy peet baty",
      imgPath: "lib/assests/Images/Laptopone.jpg",
      price: 0.99,
      category: FoodCategory.drinks,
      availableAddons: [
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
      ],
    ),
    Food(
      name: "Classic Cheese",
      description: "A juicy peet baty",
      imgPath: "lib/assests/Images/Laptopone.jpg",
      price: 0.99,
      category: FoodCategory.drinks,
      availableAddons: [
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
        Addon(name: "Extra Cheese", price: 30.9),
      ],
    )
  ];

  List<Food> get menu => _menu;
}
